# Node 1 Configuration - config-node1.toml

# Network
data-path="data"
genesis-file="../genesis.json"
network-id=1337
p2p-port=30303
rpc-http-enabled=true
rpc-http-api=["ETH","NET","QBFT","ADMIN","DEBUG"]
rpc-http-host="0.0.0.0"
rpc-http-port=8545
rpc-http-cors-origins=["*"]
host-allowlist=["*"]


# Synchronization
sync-mode="SNAP"
fast-sync-min-peers=1

# Mining/Validation
miner-enabled=true
miner-coinbase="0x0000000000000000000000000000000000000000"

# Logging
logging="INFO"

# Performance


# P2P Discovery
discovery-enabled=true
p2p-host="127.0.0.1" 
p2p-interface="0.0.0.0"
max-peers=25

# Boot nodes - Leave empty for node1 (bootnode)
bootnodes=[]

# Add to your config-node1.toml
min-gas-price=10

